# Generated by Django 5.1.3 on 2024-12-01 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.CharField(max_length=10, unique=True)),
                ('airline', models.CharField(max_length=100)),
                ('departure_airport', models.CharField(max_length=100)),
                ('departure_code', models.CharField(max_length=3)),
                ('departure_city', models.CharField(max_length=100)),
                ('departure_country', models.CharField(max_length=100)),
                ('departure_date', models.DateTimeField()),
                ('arrival_airport', models.CharField(max_length=100)),
                ('arrival_code', models.CharField(max_length=3)),
                ('arrival_city', models.CharField(max_length=100)),
                ('arrival_country', models.CharField(max_length=100)),
                ('arrival_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_seats', models.PositiveIntegerField(default=0)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=100)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='flights.flight')),
            ],
        ),
    ]
